# 数据库配置文件
# 如果存在此文件，程序会自动尝试从数据库加载配置
# 如果数据库连接失败，会回退到 config.yaml 文件

database:
  # PostgreSQL 数据库连接字符串
  dsn: "postgres://username:password@localhost:5432/gather_db?sslmode=disable"
  
  # 连接池配置
  max_open_conns: 10
  max_idle_conns: 5
  conn_max_lifetime: "1h"
  
  # 连接超时
  connect_timeout: "10s"
  read_timeout: "30s"
  write_timeout: "30s" 